---
subtitle: "Phenological characterization and modeling of diverse lentil (*Lens culinaris* Medik.) germplasm grown in multiple environments"
title: "Vignette"
author: "Derek Wright"
date: "`r Sys.Date()`"
output: 
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F, warning = F)
```

---

```{r echo = F, eval = F}
# My own data prep
library(agiler)
library(agData)
# aa <- AGILE_RawData %>% agiler_fixOutliers() %>% agiler_tidy(9, "Easy")
# write.csv(aa, "data_ALLRawData.csv", row.names = F)
#
# create DTF2 DTS2 and DTM2
r163 <- data.frame(Plot = c(4073,4074,4075), Entry = 163, Name = "PI 289079 LSP AGL", Rep = 1:3, 
                   Expt = "Bardiya, Nepal 2016", Location = "Bardiya, Nepal", PlantingDate = as.Date("2016-11-14"),
                   Year = 2016, DTF2 = 125, DTS2 = 140, DTM2 = 149)
rr <- AGILE_RawData %>% 
  agiler_fixOutliers() %>%
  agiler_tidy(9, matchColumn = "Excel", renameColumn = "Easy", na.rm = F) %>% #
  filter(Trait %in% c("DTE", "DTF", "DTS", "DTM", "Yield"), 
         !Expt %in% c("USA 2016","USA 2017"), Rep %in% 1:3) %>% 
  spread(Trait, Value) %>%
  mutate(Expt = paste(Location, Year),
         #
         DTF2 = DTF,
         DTS2 = DTS,
         DTM2 = DTM) %>%
  bind_rows(r163) %>%
  mutate(DTF2 = ifelse((Expt == "Jessore, Bangladesh 2016" & is.na(DTF2)), 104, DTF2),
         DTF2 = ifelse((Expt == "Jessore, Bangladesh 2017" & is.na(DTF2)), 103.5, DTF2),
         DTF2 = ifelse((Expt == "Bhopal, India 2016" & is.na(DTF2)),       86,  DTF2),
         DTF2 = ifelse((Expt == "Bhopal, India 2017" & is.na(DTF2)),       85,  DTF2),
         #
         DTS2 = ifelse((Expt == "Jessore, Bangladesh 2016" & is.na(DTS2)), 107, DTS2),
         DTS2 = ifelse((Expt == "Jessore, Bangladesh 2017" & is.na(DTS2)), 104, DTS2),
         DTS2 = ifelse((Expt == "Bhopal, India 2016" & is.na(DTS2)),       102, DTS2),
         DTS2 = ifelse((Expt == "Bhopal, India 2017" & is.na(DTS2)),       104, DTS2),
         DTS2 = ifelse((Expt == "Bardiya, Nepal 2016" & is.na(DTS2)),      149, DTS2),
         DTS2 = ifelse((Expt == "Bardiya, Nepal 2017" & is.na(DTS2)),      163, DTS2),
         DTS2 = ifelse((Expt == "Marchouch, Morocco 2016" & is.na(DTS2)),  151, DTS2),
         DTS2 = ifelse((Expt == "Central Ferry, USA 2018" & is.na(DTS2)),  96,  DTS2),
         #
         DTM2 = ifelse((Expt == "Jessore, Bangladesh 2016" & is.na(DTM2)), 127, DTM2),
         DTM2 = ifelse((Expt == "Jessore, Bangladesh 2017" & is.na(DTM2)), 114, DTM2),
         DTM2 = ifelse((Expt == "Bhopal, India 2016"      & is.na(DTM2)),  112, DTM2),
         DTM2 = ifelse((Expt == "Bhopal, India 2017"      & is.na(DTM2)),  114, DTM2),
         DTM2 = ifelse((Expt == "Sutherland, Canada 2017" & is.na(DTM2)),  92,  DTM2),
         DTM2 = ifelse((Expt == "Central Ferry, USA 2018" & is.na(DTM2)),  101, DTM2),
         DTM2 = ifelse((Expt == "Rosthern, Canada 2017"   & is.na(DTM2)),  82,  DTM2),
         DTM2 = ifelse((Expt == "Bardiya, Nepal 2016"     & is.na(DTM2)),  150, DTM2),
         DTM2 = ifelse((Expt == "Bardiya, Nepal 2017"     & is.na(DTM2)),  173, DTM2),
         DTM2 = ifelse((Expt == "Marchouch, Morocco 2016" & is.na(DTM2)),  173, DTM2),
         VEG = DTF - DTE,
         REP = DTM - DTF
         #DTM2 = ifelse((Location == "Jessore, Bangladesh" & is.na(DTM2)), 105, DTM2),
         )
# rr %>% filter(Entry == 161) %>% select(Entry, Expt, DTF, DTS, DTM, DTF2, DTS2, DTM2)
# oo <- rr %>% filter(DTM<DTS | DTM<DTF | DTS<DTF) %>% select(Plot, Entry, Rep, Expt, DTE,DTF,DTF2,DTS,DTM,VEG,REP)
#
# For each entry, make DTF2 = NA if at least one rep has data
#
x<-rr; trait="DTS"; k<-"Jessore, Bangladesh 2016"; i<-166
repFix <- function(x, trait) {
  trait2 <- paste0(trait,"2")
  for(k in unique(x$Expt)) {
    for(i in 1:324) {
      if(!sum(is.na(x[x$Expt == k & x$Entry == i, trait])) %in% c(0,3)) {
        x[x$Expt == k & x$Entry == i & is.na(x[,trait]), trait2] <- NA
      }
    }
  }
  x
}
# rr %>% filter(Expt == "Jessore, Bangladesh 2016", Entry == 102) %>% select(Entry, Expt, DTF,DTF2)
# rr %>% filter(Expt == "Jessore, Bangladesh 2016", Entry == 155) %>% select(Entry, Expt, DTF,DTF2)
# rr <- repFix(rr, trait = "DTF")
# rr %>% filter(Expt == "Jessore, Bangladesh 2016", Entry == 102) %>% select(Entry, Expt, DTF,DTF2)
# rr %>% filter(Expt == "Jessore, Bangladesh 2016", Entry == 155) %>% select(Entry, Expt, DTF,DTF2)
rr <- repFix(rr, trait = "DTF")
rr <- repFix(rr, trait = "DTS")
rr <- repFix(rr, trait = "DTM")
# a few entries need fixing cuz there was only 2 plots in Expt
rr <- rr %>%
  mutate(DTS2 = ifelse((Expt == "Jessore, Bangladesh 2016" & Entry %in% c(161,164,166)), 107, DTS2),
         DTM2 = ifelse((Expt == "Jessore, Bangladesh 2016" & Entry %in% c(161,164,166)), 127, DTM2),
         DTF2 = ifelse((Expt == "Jessore, Bangladesh 2016" & Entry == 161), 104, DTF2),
         DTF2 = ifelse((Expt == "Central Ferry, USA 2018" & Entry == 126), 74, DTF2),
         DTF2 = ifelse((Expt == "Central Ferry, USA 2018" & Entry == 131), 60, DTF2),
         DTF2 = ifelse((Expt == "Central Ferry, USA 2018" & Entry == 148), 66, DTF2))
#
#rr %>% filter(Entry %in%c(126,131,148), Expt =="Central Ferry, USA 2018") %>% select(Entry, DTF,DTS,DTM, REP, DTF2,DTS2,DTM2,REP2)
#
ff <- AGILE_Timeline %>% rename(Number_of_Seeds_Sown = NumberOfSeedsSown, Plot_Type = PlotType) %>%
  mutate(Expt = paste(Location, Year)) %>% 
  filter(Type == "Field Trial", Location != "Bardibas, Nepal", 
         Expt != "Central Ferry, USA 2016",
         Expt != "Central Ferry, USA 2017") %>%
  select(-Type, -E, -riemStation, -tmz, -CropYearStart, -CropYearEnd, -Area, -Collector)
write.csv(ff, "data/data_Info.csv", row.names = F)
 #%>%
#mutate(MaxDTF = ifelse(Location == "Bardiya, Nepal", MaxDTF + 3, MaxDTF))
#
rr <- rr %>% #left_join(select(ff, MacroEnv, Expt), by = "Expt") %>%
  mutate(VEG2 = DTF2 - DTE,
         REP2 = DTM2 - DTF2) %>%
  select(Plot, Entry, Name, Rep, Expt, Location, Year, PlantingDate,
         DTE, DTF, DTF2, DTS, DTM)
write.csv(rr, "data/data_Raw.csv", row.names = F)
#
ee <- AGILE_EnvData_TP %>% 
  filter(!Expt %in% c("USA 2016", "USA 2017")) %>%
  mutate(Expt = paste(Location, Year)) %>%
  left_join(select(ff, MacroEnv, Expt), by = "Expt") %>% 
  mutate(Expt = paste(Location, Year))
#
write.csv(ee, "data/data_Env.csv", row.names = F)
#
#pp <- read.csv("11_DTF_pca_new_DTF8.csv") %>% #AGILE_DTF_PCA %>% 
#  select(Entry, Cluster) %>% mutate(Cluster = factor(Cluster))
# write.csv(pp, "data_DTF_pca_old.csv", row.names = F)
cc <- AGILE_MacroEnv %>% select(Origin = Country, MacroEnv)
#btpc <- readRDS("model_coefs_TP.rds") %>% select(Entry,bt,pc)
ldp <- AGILE_LDP %>% #left_join(pp, by = "Entry") %>% 
  #mutate(Origin = ifelse(Origin=="Unknown","ICARDA", Origin)) %>%
  #left_join(cc, by = "Origin") %>%
  select(Entry, Name, Origin, Source, Lat = Latitude, Lon = Longitude, Synonyms=Syns)
  #mutate(Id = as.character(Entry),
  #       S_Breed = ifelse(Origin %in% c("India","Bangladesh","Pakistan","Unknown"), Origin, "Other"),
  #       M_Breed = ifelse(Origin %in% c("Spain","Italy","Morocco","Greece","Portugal","France"), Origin, "Other"),
  #       T_Breed = ifelse(Origin %in% c("Canada","USA"), Origin, "Other") )
#ldp <- AGILE_LDP #%>% select(Entry, Name, Origin)
write.csv(ldp, "data/data_LDP.csv", row.names = F)
#
ct <- agData_FAO_Country_Table %>% 
  filter(Country %in% unique(ldp$Origin),
         ISO2 != "MK", FAO_TABLE_NAME != "Ethiopia PDR") %>%
  select(-FAO_TABLE_NAME)
write.csv(ct, "data/data_Countries.csv", row.names = F)
#
rr %>% filter(Entry %in% c(161,164,166), Expt == "Jessore, Bangladesh 2016")
rr %>% filter(Entry == 161, Expt == "Jessore, Bangladesh 2016")
rr %>% filter(Entry == 163, Location == "Bardiya, Nepal")
rr %>% filter(Location == "Central Ferry, USA", Entry %in% c(126,131,148))
#
detach("package:agiler", unload = T)
```

---

```{r eval = F}
colors <- c("darkred",   "darkorange3", "darkgoldenrod2", "deeppink3", 
            "steelblue", "darkorchid4", "cornsilk4",      "darkgreen")
theme_AGL <- theme_bw() + theme(strip.background = element_rect(fill = "White"))
names_Expt <- c("Rosthern, Canada 2016",    "Rosthern, Canada 2017",
                "Sutherland, Canada 2016",  "Sutherland, Canada 2017", 
                "Sutherland, Canada 2018",  "Central Ferry, USA 2018",
                "Bhopal, India 2016",       "Bhopal, India 2017",
                "Jessore, Bangladesh 2016", "Jessore, Bangladesh 2017",
                "Bardiya, Nepal 2016",      "Bardiya, Nepal 2017",
                "Cordoba, Spain 2016",      "Cordoba, Spain 2017",
                "Marchouch, Morocco 2016",  "Marchouch, Morocco 2017",
                "Metaponto, Italy 2016",    "Metaponto, Italy 2017" )
xx <- readRDS("model_18_d.rds") %>% 
  mutate(Expt = factor(Expt, levels = names_Expt)) %>%
  left_join(read.csv("data/data_PCA_Results.csv"), by = "Entry") %>%
  mutate(Cluster = factor(Cluster))
# plot for business card
x1 <- xx %>% filter(Expt == "Rosthern, Canada 2017")
mp1 <- ggplot(x1, aes(x = DTF, y = DTF_Predict, color = Cluster)) + 
  geom_point(size = 0.5) + geom_abline() +
  facet_grid(.~Expt, scales = "free") +
  theme_AGL +
  theme(legend.position = "none") +
  scale_color_manual(values = colors) +
  scale_x_continuous(breaks = seq(35,180,5), minor_breaks = seq(35,180,1)) +
  scale_y_continuous(breaks = seq(35,180,5), minor_breaks = seq(35,180,1)) +
  labs(#title = "Days To Flower | Rosthern, Canada 2017",
       x = NULL, y = NULL)
x1 <- xx %>% filter(Expt == "Cordoba, Spain 2017")
mp2 <- ggplot(x1, aes(x = DTF, y = DTF_Predict, color = Cluster)) + 
  geom_point(size = 0.5) + geom_abline() +
  facet_grid(.~Expt, scales = "free") +
  theme_AGL +
  theme(legend.position = "none") +
  scale_color_manual(values = colors) +
  scale_x_continuous(breaks = seq(35,180,10), minor_breaks = seq(35,180,5)) +
  scale_y_continuous(breaks = seq(35,180,10), minor_breaks = seq(35,180,5)) +
  labs(#title = "Days To Flower | Rosthern, Canada 2017",
       x = NULL, y = NULL)
x1 <- xx %>% filter(Expt == "Jessore, Bangladesh 2017")
mp3 <- ggplot(x1, aes(x = DTF, y = DTF_Predict)) + 
  geom_point(size = 0.5) + geom_abline() +
  facet_grid(.~Expt, scales = "free") +
  theme_AGL +
  scale_x_continuous(breaks = seq(35,180,10), minor_breaks = seq(35,180,5)) +
  scale_y_continuous(breaks = seq(35,180,10), minor_breaks = seq(35,180,5)) +
  labs(#title = "Days To Flower | Rosthern, Canada 2017",
       x = NULL, y = NULL)
mp <- ggarrange(mp1, mp2,  nrow = 2, ncol = 1, align = "hv")
mp <- annotate_figure(mp, left = "Predicted",
                      top    = text_grob("Days to Flower", hjust = 0.375),
                      bottom = text_grob("Observed", hjust = 0.375))
ggsave("Temp_F5_2.png", mp, width = 2, height = 3.5)
```


```{r echo = F, eval = F}
saveRDS(ee, file = "shiny_ee.rds")
saveRDS(ff, file = "shiny_ff.rds")
#
# Prep data
xx <- rr %>% filter(!is.na(RDTF)) %>%
  left_join(select(ff, Expt,T_mean,P_mean), by = "Expt")
m1 <- train(RDTF ~ T_mean, data = xx, method = "lm")
m2 <- train(RDTF ~ P_mean, data = xx, method = "lm")
m3 <- train(RDTF ~ T_mean + P_mean, data = xx, method = "lm")
xx <- data.frame(Temperature = m1[[4]]$Rsquared,
                 Photoperiod = m2[[4]]$Rsquared,
                 `Temperature + Photoperiod` = m3[[4]]$Rsquared)
xx
```
